Pfe\FournisseurBundle\Entity\Boncommande:
    type: entity
    table: boncommande
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        numero:
            type: integer
            unsigned: false
            nullable: true
        dateMouvement:
            type: datetime
            nullable: true
            column: date_mouvement
        objetBc:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: objet_bc
        designationLivraison:
            type: string
            length: 45
            fixed: false
            nullable: true
            column: designation_livraison
    manyToOne:
        offre:
            targetEntity: Offre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                offre_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
